NetsoftHoldings/netsoft-danger

.gitignore, Dangerfile, circle.yml, lib/netsoft-danger/version.rb
add in circle.yml so we can build and deploy via circle
=> circle support

Dangerfile, lib/netsoft-danger/version.rb, netsoft-danger.gemspec
add some more checks for things we don't want in spec files
=> better spec checking

Dangerfile, lib/netsoft-danger/version.rb
for cases where we are adding applying a migration inherited from a gem
=> relax the schema rb checks

Dangerfile, lib/netsoft-danger/version.rb
=> fix checking for fit, fdescribe, etc..

Dangerfile, lib/netsoft-danger/version.rb
this will help better track changes to the icon font
=> add check to ensure hubstaff-icon changes are in their own commit

bin/tag_check.sh, circle.yml
- prevents oopses when version.rb not updated in sync with tag
=> add tag check step to deploy process

Dangerfile, lib/netsoft-danger/version.rb
make sure we check for fcontext as well
=> also check for fcontext in specs

dangerfiles/pr.js
=> Basic rules for a pr

dangerfiles/pr.js
now label checks will actually work
=> correct checking for labels in peril file.

settings-peril.json
we are starting to use perl everywhere
=> don't ignore the danger repo anymore

Dangerfile, dangerfiles/pr.js, lib/netsoft-danger/version.rb
- Remove the rules that we can handle in peril from the Dangerfile
- also add in the Merge commit detection rule to peril
=> remove rules now covered by perl from the ruby dangerfile

Dangerfile, netsoft-danger.gemspec
Update hubstaff-font detection due to changes on how we build it..
=> update hubstaff-font detection

Dangerfile, lib/netsoft-danger/version.rb
when the gemfile.lock changes ensure that 1.15.2 is used
=> require bundler 1.15.2 in the Gemfile.lock

Dangerfile, bin/netsoft-circle, lib/netsoft-danger/version.rb, netsoft-danger.gemspec
Description:
Add CLI to configure CircleCI.
=> Add `netsoft-circle` executable

Dangerfile, lib/netsoft-danger/version.rb
fix the ENV check to determine if we are doing the 2.0 style artifacts
=> fix circle 1.0 usage

.circleci/config.yml, dangerfiles/pr.js, package.json, yarn.lock
check that a PR has a milestone
=> check that a PR is linked to a milestone before allowing merging

Dangerfile
Add in package.json checks like the gemfile checks
=> Add checks for package.json commits

.circleci/config.yml, .rubocop.yml, Dangerfile, Gemfile, Rakefile, bin/netsoft-circle, lib/netsoft-danger/version.rb, netsoft-danger.gemspec
Adds rubocop.
Some rules disabled as they mess w/ the Dangerfile in incompatible ways (breaking danger) or make the lines too long to be readable.
=> Add rubocop

CHANGELOG.md, Dangerfile
- migration label when changes exist to migrations or schemas
- security label based on branch name
=> auto manage setting some labels

CHANGELOG.md, Dangerfile, yarn.lock
In preparation of us switching to conventional commits..
=> allow conventional commit format for migration, gemfile and package commits

CHANGELOG.md, dangerfiles/pr.js
Support the new 'product review needed' label and the new names for core review needed
=> feat(Peril): support new label names and product review labels

.github/PULL_REQUEST_TEMPLATE.txt
Use the PR template recommended by Vanta:
https://github.com/VantaInc/sdlc-templates/blob/master/.github/pull_request_template.md.
The template includes basic development and security guidelines.
=> Improve the format of PULL_REQUEST_TEMPLATE

Dangerfile, bin/netsoft-circle
Add brakeman support in similar to rubocop approach.
=> feat(Brakeman): Report brakeman to PRs

.github/PULL_REQUEST_TEMPLATE.md
Just changing PR template extension
- Source: <Issue link or Spec Link>
- UAT: <UAT Link>
- QA: <QA Task Link here>
- Review app: <Link to Heroku>
=> Fix pull request template to satisfy Vanta

CHANGELOG.md, lib/netsoft-danger/version.rb, netsoft-danger.gemspec
update danger so it works with GH's current APIs
- Source: <Issue link or Spec Link>
- UAT: <UAT Link>
- QA: <QA Task Link here>
- Review app: <Link to Heroku>
=> update danger version
